"""Local Chromium checks. Uses set_content; no external browser network is needed."""
from pathlib import Path
import json, os
from playwright.sync_api import sync_playwright, expect
ROOT = Path(__file__).resolve().parents[1]
OUT=Path(os.environ.get('NYE_QA_OUTPUT', str(ROOT/'.local/qa')))
OUT.mkdir(parents=True, exist_ok=True)
BROWSER=os.environ.get('PLAYWRIGHT_CHROMIUM_EXECUTABLE')
HTML = (ROOT / 'Sour-Boule-New-Year-Preview.html').read_text()
results=[]
def record(name, condition=True):
    if not condition: raise AssertionError(name)
    results.append({'test':name,'status':'PASS'})
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=BROWSER,headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
    page=context.new_page();errors=[];requests=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:requests.append(r.url))
    page.set_content(HTML);expect(page.locator('#sb-title')).to_be_visible()
    record('Opening preview has a live ticking simulation and labeled first-name input',page.locator('#sb-minutes').inner_text()=='10')
    record('Hero year remains ivory, not gold',page.locator('.sb-year').evaluate('(e)=>getComputedStyle(e).color')=='rgb(245, 240, 230)')
    record('Opening hero shows 2026 with the matching accessible label',page.locator('.sb-year').inner_text()=='2026' and page.locator('.sb-year').get_attribute('aria-label')=='2026')
    record('Preview explicitly says simulated time and no real rewards', 'No real rewards' in page.locator('.sb-previewbar').inner_text())
    record('Registration offer explicitly requires no purchase', 'No purchase required.' in page.locator('.sb-offer').inner_text())
    page.screenshot(path=str(OUT/'desktop-opening.png'),full_page=True)
    page.get_by_role('textbox',name='Your first name').fill('Jamie')
    page.get_by_role('button',name='Count me in').click()
    expect(page.locator('.sb-card h2')).to_contain_text('Jamie')
    record('Registration produces a clearly simulated registered state')
    record('Registered and pending rules require no purchase', 'No purchase required.' in page.locator('.sb-rules').inner_text())
    page.get_by_role('button',name='Final minute',exact=True).click();page.wait_for_timeout(150)
    expect(page.locator('#sb-title')).to_contain_text('One minute')
    record('Final-minute hero still shows 2026',page.locator('.sb-year').inner_text()=='2026')
    page.get_by_role('button',name='Last 10 seconds',exact=True).click();page.wait_for_timeout(150)
    record('Final-minute ball has descended',page.locator('.sb-ball').evaluate('(e)=>new DOMMatrix(getComputedStyle(e).transform).m42')>100)
    page.screenshot(path=str(OUT/'desktop-final-minute.png'),full_page=True)
    page.get_by_role('button',name='Midnight',exact=True).click()
    expect(page.locator('#sb-title')).to_contain_text('Happy')
    record('Midnight hero shows 2027 with the matching accessible label',page.locator('.sb-year').inner_text()=='2027' and page.locator('.sb-year').get_attribute('aria-label')=='2027')
    expect(page.locator('.sb-ticket')).to_be_visible()
    record('Midnight produces Happy New Year and a watermarked sample pass')
    record('Pass states one free cookie, no purchase required, and January 3 deadline', 'No purchase required.' in page.locator('.sb-ticket').inner_text() and 'January 3, 2027' in page.locator('.sb-ticket').inner_text())
    page.wait_for_timeout(4000);page.screenshot(path=str(OUT/'desktop-midnight.png'),full_page=True)
    code=page.locator('.sb-ticket code').inner_text()
    record('Sample pass has exactly five digits, in demo-only 0xxxx range',len(code)==5 and code.isdigit() and code[0]=='0')
    record('Ball uses curved facets and separate twinkling highlights',page.locator('.sb-crystal-twinkle').count()==8)
    page.evaluate("() => { window.savedPassText=[]; const original=CanvasRenderingContext2D.prototype.fillText; CanvasRenderingContext2D.prototype.fillText=function(text,...args){window.savedPassText.push(String(text));return original.call(this,text,...args);}; }")
    with page.expect_download() as download:
        page.get_by_role('button',name='Save sample pass as an image').click()
    download.value.save_as(str(OUT/'sample-cookie-pass.png'))
    record('Save pass creates a real image file with a TEST ONLY stamp')
    record('Saved PNG says no purchase required with no former minimum', page.evaluate("savedPassText.includes('No purchase required.') && !savedPassText.some(t=>t.includes('$5') || t.includes('With a purchase'))"))
    page.get_by_role('button',name='12:05 / Return',exact=True).click()
    expect(page.locator('.sb-placeholder')).to_be_visible()
    record('Return placeholder remains 2027 after midnight',page.locator('.sb-year').inner_text()=='2027')
    record('Return uses a placeholder rather than a copied seasonal website')
    page.screenshot(path=str(OUT/'desktop-return.png'),full_page=True)
    page.locator('[data-action="pass"]').first.click()
    expect(page.locator('.sb-ticket')).to_be_visible()
    record('Earned sample pass remains accessible after takeover',page.locator('.sb-ticket code').inner_text()==code)
    page.get_by_role('button',name='Staff flow',exact=True).click()
    expect(page.locator('#station-location')).to_contain_text('Fort Worth')
    record('Station opens already signed in for the preview, with no location picker',page.locator('#location').count()==0)
    page.locator('#code').fill(code)
    page.get_by_role('button',name='Check code',exact=True).click()
    record('Five-digit input verifies with no extra purchase checkbox',page.get_by_role('checkbox').count()==0 and page.get_by_role('button',name='Redeem cookie').is_enabled())
    record('Staff sees no-purchase terms and no extra confirmation control', 'No purchase required.' in page.locator('.sb-station-note').inner_text() and page.get_by_role('checkbox').count()==0)
    page.screenshot(path=str(OUT/'staff-ready.png'),full_page=True)
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=str(OUT/'mobile-staff-ready.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':1000})
    page.get_by_role('button',name='Redeem cookie').click()
    expect(page.locator('#result')).to_contain_text('Give one cookie')
    record('Proposed staff flow completes a clearly simulated redemption')
    page.get_by_role('button',name='Next guest',exact=True).click()
    page.locator('#code').fill(code)
    page.get_by_role('button',name='Check code',exact=True).click()
    expect(page.locator('#result')).to_contain_text('Already used')
    record('A second sample redemption is rejected in the preview')
    page.screenshot(path=str(OUT/'staff-simulation.png'),full_page=True)
    page.get_by_role('button',name='Willow Bend phone',exact=True).click()
    page.locator('#code').fill(code);page.get_by_role('button',name='Check code',exact=True).click()
    expect(page.locator('#result')).to_contain_text('Already used')
    record('Other simulated location sees the used pass immediately')
    page.locator('#code').fill('01234');page.get_by_role('button',name='Check code',exact=True).click()
    expect(page.locator('#result')).to_contain_text('Code not found')
    record('Unknown five-digit demo code has no redeem option',page.get_by_role('button',name='Redeem cookie',exact=True).count()==0)
    record('Staff input requests numeric phone keyboard and caps input at five',page.locator('#code').get_attribute('inputmode')=='numeric' and page.locator('#code').get_attribute('maxlength')=='5')
    for width in [320,375,390,768,1366,1440]:
        page.set_viewport_size({'width':width,'height':844});page.wait_for_timeout(50)
        record(f'Staff layout has no horizontal overflow at {width}px',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.set_viewport_size({'width':390,'height':844})
    page.locator('#code').fill('04271')
    page.screenshot(path=str(OUT/'mobile-staff.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':1000})
    page.get_by_role('button',name='Reset',exact=True).click()
    page.get_by_role('button',name='Connection loss',exact=True).click()
    expect(page.locator('#sb-network')).to_contain_text('Reconnecting')
    record('Connection-loss simulation shows reconnect state')
    page.get_by_role('button',name='Connection loss',exact=True).click()
    expect(page.locator('#sb-network')).to_contain_text('Preview only')
    record('Successful reconnect clears the obsolete connection error',page.locator('#sb-error').inner_text()=='')
    for width,height in [(320,568),(375,812),(390,844),(768,1024),(1366,768),(1440,900)]:
        page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(100)
        record(f'No horizontal page overflow at {width}px',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
        if width==390:
            page.screenshot(path=str(OUT/'mobile-opening.png'),full_page=True)
            record('Mobile guest header and action targets are at least 44px high',page.locator('.sb-header button, .sb-primary, .sb-footer button').evaluate_all('(els)=>els.every(e=>e.getBoundingClientRect().height>=44)'))
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('button',name='Cookie unlocked',exact=True).click();expect(page.locator('.sb-ticket')).to_be_visible()
    page.screenshot(path=str(OUT/'mobile-pass.png'),full_page=True)
    record('Reward layout does not overflow on mobile',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.emulate_media(reduced_motion='reduce');page.wait_for_timeout(100)
    record('OS reduced-motion preference disables ball motion and fireworks',page.locator('.sb-app').get_attribute('data-motion')=='off' and page.locator('.sb-fireworks').evaluate('(e)=>getComputedStyle(e).display')=='none')
    record('No unhandled JavaScript exceptions across preview flows',not errors)
    record('Self-contained preview makes no external network requests',not requests)
    # Test focus/data preservation across a NATURAL phase transition, not a preview reset.
    second=context.new_page();second.clock.install();second.set_content(HTML);second.clock.run_for(100)
    second.get_by_role('textbox',name='Your first name').fill('Still typing')
    second.clock.fast_forward(540100);second.clock.run_for(100)
    record('Name typed across 11:59 transition is not erased',second.get_by_role('textbox',name='Your first name').input_value()=='Still typing')
    browser.close()
(OUT/'ui-tests.json').write_text(json.dumps({'environment':'Chromium / local set_content / no remote network','checks':results,'count':len(results)},indent=2))
print(json.dumps({'checks':len(results),'pass':len(results),'errors':errors},indent=2))
